apiVersion: v1
kind: Service
metadata:
  name: teg-envoy-gateway
  namespace: '{{ .Release.Namespace }}'
  labels:
    control-plane: teg-envoy-gateway
  {{- include "teg.labels" . | nindent 4 }}
spec:
  selector:
    control-plane: teg-envoy-gateway
  {{- include "teg.selectorLabels" . | nindent 4 }}
  ports:
  - name: sds
    port: 18000
    targetPort: 18000
